"""update disposable table

Revision ID: 2f721322a08e
Revises: 2a56df5f1a29
Create Date: 2021-07-22 20:45:45.219365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f721322a08e'
down_revision = '2a56df5f1a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disposable', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'disposable', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disposable', type_='foreignkey')
    op.drop_column('disposable', 'user_id')
    # ### end Alembic commands ###
