"""remove extra email

Revision ID: 7308e51665cf
Revises: a1f20a53b2f7
Create Date: 2021-07-08 12:21:31.325189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7308e51665cf'
down_revision = 'a1f20a53b2f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
