"""add_disposable_booking

Revision ID: a1f20a53b2f7
Revises: f16e5d009c0a
Create Date: 2021-07-08 11:58:02.361545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f20a53b2f7'
down_revision = 'f16e5d009c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disposable_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('disposable_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['disposable_id'], ['disposable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disposable_bookings')
    # ### end Alembic commands ###
